# Site settings
title:       Phil Puleo
email:       mail@phillippuleo.com
author:      Phil Puleo
description: "Tips, patterns, and thoughts on modern web development."
baseurl:     ""
url:         "http://phillippuleo.com"

# Google analytics
google_analytics: UA-30272735-1

# Optional features
animated:           true
show_related_posts: false
show_post_footers:  false

# Gems
gems: [jekyll-paginate]

# Social icons
show_social_icons: true
github_username: ppuleo
twitter_username:
google_plus_id:
linkedin_username: phillippuleo
bitcoin_url:
paypal_url:
flattr_button:
cv: "/images/puleo_resume.pdf"

# Build settings
markdown: kramdown
syntax_highlighter: rouge
permalink: pretty
paginate: 5
sass:
  compressed: true
